// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input C:/Users/peter.DESKTOP-ADFB1L1/qmk_firmware2/monarch_logo.bmp --output C:/Users/peter.DESKTOP-ADFB1L1/qmk_firmware2 --format mono256 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_monarch_logo_length;
extern const uint8_t  gfx_monarch_logo[1618];
